##########
# collectionbuilder-gh
# Jekyll Digital Collection Generator, designed for GitHub Pages
# https://github.com/CollectionBuilder/collectionbuilder-gh
##########

##########
# URL VARIABLES [optional if using GitHub Pages!]
#
# url is site domain, full URL to the production location of your collection
# on GitHub Pages follows the pattern username.github.io
#url: https://collectionbuilder.github.io 
# baseurl is path to location on the domain if necessary e.g. /digital/hjccc
# on GitHub Pages it is your github repository's name prefixed with a /
#baseurl: /collectionbuilder-gh 
# location of code, the full url to your github repository
source-code: https://github.com/amarr02/Parson-Site-Website

##########
# SITE SETTINGS
#
# title of site appears in banner
title: Not Just A Site
# tagline, a short phrase that will appear throughout the site in the top banner
tagline: Discussions of the Problematic Archeology of Ontario's Indigenous Sites
# description appears in meta tags and other locations
# this description might appear in search result lists, keep around 160 characters max
description: "‘Not Just a Site’ Show Notes
Title: Not Just a Site: Episode 1
The Parsons Site:
The Issues of Ontarian Archeology and the Path to Reconciliation
--
Authors:
Emily Strba
Fraser Williston
Amar Ramic
--
Description:
“As much as I admire Archeology, it is a science of guesswork.” - Prof. Jon Johnson

Professors Jon Johnson and Gary Warrick join us in today’s episode experts in the field of Huron-Wendat archeology, giving insight into the complexity of an archeological site: Parsons.

Today’s episode will discuss the physical history of Parsons and its place as a public history site. By discussing the indigenous history and archeology of the Parsons Site we highlight the shortcomings of Ontarian archeological practices of recent years. The artefacts of Parsons are largely missing, with little idea of where they may be. Our interviews with Dr. Johnson and Dr. Warrick bring us closer to the heart of the issue of what needs to be done to allow for reconciliation to take place, with Parsons being at the forefront of this process.
--
Acknowledgments:
We thank Dr. Jon Johnson and Dr. Gary Warrick for their time in allowing us to interview them on the history of the Parsons Site and their views surrounding it.
--
Guests:
Dr. Jon Johnson and Dr. Gary Warrick
--
References:
Emerson, J. Norman. Understanding Iroquois Pottery in Ontario : A Rethinking. Mississauga: Ontario Archaeological Society, 1968.

First Story Toronto: Exploring The Indigenous History of Toronto! https://firststoryblog.wordpress.com/aboutfirststory/ 

Hunter, Andrew Frederick. Huron Village Sites. Toronto: Warwick Bros. & Rutter, 1907.

Pfeiffer, Susan, and Louis Lesage. “The Repatriation of Wendat Ancestors, 2013.” Canadian
Journal of Archaeology Vol. 38, Issue 1. (2014): 5–12.

Robertson, David, and Williamson, Ronald. “The Archaeology of the Parsons Site: Summary
and Conclusions.” Ontario Archaeology, Vol. 65/66 (1998): 146-148.

Robertson, David, Williamson, Ronald, and Cooper, Martin. “The 1989-90 Excavations at the Parsons Site: Introduction and Retrospect” Ontario Archaeology, Vol. 65/66 (1998): 4-16.

Sandberg, L. Anders, Jon Johnson, Rene Gualtieri, and Louis Lesage. “Re-Connecting with a
Historical Site: On Narrative and the Huron-Wendat Ancestral Village at York
University, Toronto, Canada.” Ontario History Vol. 113, Issue 1 (2021): 80–105.

Warrick, Gary, and Bonnie Glencross, and Louis Lesage. “The Importance of Minimally Invasive Remote Sensing Methods in Huron-Wendat Archaeology” Advances in Archaeological Practice Vol. 9, Issue 3. (2021): 238–249. 

--
Music Credits:
“Forest Lullabye”: Created by Asher Fulero. From YouTube Library.."
# creator of the digital collection, to appear in meta tags; we typically use our GitHub usernames but feel free to just use your name
author: Amar Ramic, Fraser Williston, and Emily Strba

##########
# COLLECTION SETTINGS
#
# Set the metadata for your collection (the name of the csv file in your _data directory that describes the objects in your collection) 
# Use the filename of your CSV **without** the ".csv" extension! E.g. _data/demo-metadata.csv --> "demo-metadata"
metadata: parsons-site-metadata

##########
# Site/Organization Branding 
#   Uncomment these and enter information for your organization (replacing the CDIL links and name below) if you'd like to brand your site with a logo
#
# organization-name: "Center for Digital Inquiry and Learning (CDIL)"
# organization-link: https://cdil.lib.uidaho.edu/
# organization-logo-banner: https://cdil.lib.uidaho.edu/storying-extinction/assets/img/cdil.png
# organization-logo-nav: https://cdil.lib.uidaho.edu/assets/img/logo.png



##########
# GOOGLE SERVICES [optional!]
#
# leave these blank or comment out to NOT include google code. See docs/google.md
#
# Add your google-analytics-id to automatically add the embed code, e.g. "G-123XXXXXX"
# google-analytics-id:
# to populate a Google CSE add the id, e.g. "002151703305773322890:1pu3smhw1t8"
# google-cse-id: 

##########
# ROBOTS EXCLUDE
#
# set noindex to true if you do NOT want Google to index your site
# noindex: true 

##########
# BUILD SETTINGS 
#
# Note: use environment variable on build command to include analytics
# JEKYLL_ENV=production jekyll build
# (this is done automatically by gh-pages build)
#
# ignore stuff
exclude: [docs/, Rakefile, README.md, LICENSE, CITATION.cff, CODE_OF_CONDUCT.md, CONTRIBUTING.md]
# compress CSS output
sass:
  style: compressed
